version: "3"
services:

  vertx:
    build: ./Consulta
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=universidad
      - MYSQL_USER=performance
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
