version: "3"
services:

  db:
    build: ./db
    environment:
      - MYSQL_DATABASE=universidad
      - MYSQL_USER=performance
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    command: "mysqld --max_connections=100000"
    ports:
      - "3306:3306"
  jetty:
    build: .
    ports:
      - "8080:8080"
